# Generated by Django 3.1.4 on 2020-12-31 19:34

import builtins
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.RenameField(
            model_name='items',
            old_name='descricao',
            new_name='mensagem',
        ),
        migrations.RemoveField(
            model_name='items',
            name='imagens_urls',
        ),
        migrations.AddField(
            model_name='items',
            name='assunto',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='email',
            field=models.EmailField(default=builtins.id, max_length=100),
            preserve_default=False,
        ),
    ]
