# Generated by Django 3.1.4 on 2021-01-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_auto_20201231_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('nome',), 'verbose_name_plural': 'Items'},
        ),
    ]
